version: '3'

services:
  web:
    build: ./web
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - 5000:5000
    env_file:
      - ./web/.env.prod
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./web/.env.prod

volumes:
  postgres_data:
